### ISSUE TITLE
The library chatbotAI 

### ISSUE THREAD

**Issue by babypastorkayvon** [PratikSavla/aio-bot#4]
It has errors as multifunctionalCall and responses don't have member functions of that __ini__.py library.

**Comment by PratikSavla** [comment]
Hey @babypastorkayvon Thanks for pointing the error out. The [ChatbotAI](https://pypi.org/project/chatbotAI/) updated their library and the support for multifunctionalCall and responses was removed in it. I have updated the  [utils.py](https://github.com/PratikSavla/aio-bot/blob/master/utils.py) file to support the recent versions and added the working helper library versions in the [requirements.txt](https://github.com/PratikSavla/aio-bot/blob/master/requirements.txt) for future proofing it. 
Closing this issue.
